[phases.setup]
commands = [
  "python3 -m venv venv",
  "source venv/bin/activate",
  "pip install -r server/requirements.txt"
]

[phases.build]
commands = []

[phases.start]
commands = [
  "python3 server/app.py"
]
